export const API_BASE_URL = 'http://192.168.1.102:4100';
export const API_ENDPOINTS = {
  login: '/api/mobile/auth/login',
  logout: '/api/mobile/auth/logout',
  attendance: '/api/mobile/attendance/punch-in',
  checkout: '/api/mobile/attendance/checkout',
  history: '/api/mobile/attendance/history',
  profile: (fkEmpId: number) => `/api/mobile/attendance/employee/${fkEmpId}`,
  status: (fkEmpId: number) => `/api/mobile/attendance/status/${fkEmpId}`,
  liveLocation: '/api/mobile/attendance/live-location',
  liveLocationConfig: '/api/mobile/attendance/live-location/config',
  profileImage: '/api/mobile/attendance/profile/image',
  config: '/api/mobile/attendance/config',
  geolocations: '/api/mobile/hrm/admin/hl-geolocations',
  leaveApply: '/api/mobile/leave/apply',
  leaveHistory: '/api/mobile/leave/history',
  leaveTypes: '/api/mobile/leave/types',
  leaveBalance: '/api/leave-requests/balance',
  updateLeaveBalance: '/api/leave-requests/update-balance',
  dailyTasks: '/api/daily-tasks',
  dailyTask: (id: number) => `/api/daily-tasks/${id}`,
  securityQuestions: '/api/auth/security-questions',
  employeeSecurityQuestion: '/api/auth/employee-security-question',
  forgotPasswordValidate: '/api/auth/forgot-password/validate',
  forgotPasswordReset: '/api/auth/forgot-password/reset',
};

